identifier: TCA.Docker.CS2
version: 1.0.0
author: TCAdmin
name: Counter-Strike 2
shortDescription: CS2 docker config for TCAdmin 3
longDescription: |
  # CS2
  
  **For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2. This Docker image contains the dedicated server of the game.
  
  ## Available Container Image Repositories

  - Docker Hub: `joedwards32/cs2`
  - GitHub: `ghcr.io/joedwards32/cs2`

  ## Key Features
  - **ISO downloader**
  - **KVM acceleration**
  - **Web-based viewer**

  ## System Requirements

  Minimum system requirements are:
  - 2 CPUs
  - 2GiB RAM
  - 60GB of disk space for the container or mounted as a persistent volume on `/home/steam/cs2-dedicated/`
  - Note: More space may be required if you plan to install mods

  ## What's new in 1.0.0
  - Initial release

icon: https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/f75dd04fa12445a8ec43be65fa16ff1b8d2bf82e.jpg
images:
  - https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/header.jpg
tags:
  - Docker
files:
  - identifier: "docker_config"
    path: CS2.json
    type: DockerConfig
    optional: false