identifier: TCA.Games.MC
version: 1.0.9
author: TCAdmin
name: Minecraft
shortDescription: Minecraft game config for TCAdmin 3
longDescription: |
  # Minecraft (MC)
  
  **Minecraft (MC)** is a 3D sandbox adventure game developed by Mojang Studios where players can interact with a fully customizable three-dimensional world made of blocks and entities. Its diverse gameplay options allow players to choose the way they play, creating countless possibilities.
  
  ## Key Features
  - **Minecraft modpacks**
  - **Command line manager**
  
  ## What's new in 1.0.9
  - Fixed NeoForge version when installing modpacks.

icon: https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Logo_Minecraft.png/960px-Logo_Minecraft.png
images:
  - https://img.primaservers.dk/minecraft/index.php
tags:
  - Game
  - Windows
  - Linux
files:
  - identifier: "game_config_windows"
    path: Minecraft - Windows.json
    type: GameConfig
    optional: false
  - identifier: "game_config_linux"
    path: Minecraft - Linux.json
    type: GameConfig
    optional: false
