identifier: TCA.Themes.Trasparent
version: 1.0.0
author: TCAdmin
name: TCAdmin Transparent
shortDescription: Default TCAdmin theme with transparency
longDescription: |
  # TCAdmin Transparent
  
  **TCAdmin Transparent** is similar to the default theme but with transparency effect.
  
  ## What's new in 1.0.6
  - Initial release

icon: <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 455.56 455.56" xml:space="preserve" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <polygon style="fill:#E2BAB5;" points="168.475,227.78 126.355,269.9 84.235,227.78 126.355,185.67 "></polygon> <polygon style="fill:#E2BAB5;" points="371.325,227.78 329.215,269.9 287.095,227.78 329.215,185.67 "></polygon> <polygon style="fill:#B6CCE0;" points="371.325,312.01 227.785,455.56 84.235,312.01 126.355,269.9 227.785,371.32 329.215,269.9 "></polygon> <polygon style="fill:#B09FB7;" points="329.215,269.9 227.785,371.32 126.355,269.9 168.475,227.78 227.785,287.09 287.095,227.78 "></polygon> <rect x="185.846" y="185.841" transform="matrix(0.7071 -0.7071 0.7071 0.7071 -94.3481 227.7835)" style="fill:#8B7496;" width="83.877" height="83.877"></rect> <polygon style="fill:#E59683;" points="329.215,185.67 287.095,227.78 227.785,168.47 168.475,227.78 126.355,185.67 227.785,84.24 "></polygon> <polygon style="fill:#E2BAB5;" points="227.785,0 371.325,143.55 329.215,185.67 227.785,84.24 126.355,185.67 84.235,143.55 "></polygon> </g></svg>

tags:
  - Theme
  
files:
  - identifier: "theme_config_transparent"
    path: TCAdmin Transparent.json
    type: ThemeConfig
    optional: false